### PR TITLE
Colibri locations

### PR DESCRIPTION
**Pull request by vpnarea**
New locations using different keys/certs.

### CODE REVIEW

**Review by Zomboided — CHANGES_REQUESTED** [review]
This won't work.

You're referencing a file ca.colibri.crt and not using it anywhere.  The #CERT tag will always resolve to ca.crt.  Celo VPN uses non standard file names, check out how it's done there.

You've added a bunch of #REMOVE1 and #REMOVE2 but you're not updating the LOCATIONS.txt to indicate which location is using which tag and as a result, everything tagged will get removed, rather than depending on the location, which is what I think you're trying to do?

It's a little bit weird that you're using user key/cert for everyone - if you're intending this to be a per user thing with each user having their own, then I need to make changes in the code.

And finally, and I should have noticed this previously, resolv-retry should be 30 otherwise I don't time out in the add-on properly.

**Comment by vpnarea** [comment]
This is what I have in the promised `LOCATIONS.txt` (e.g.):

```
US Colibri-US (UDP),138.68.60.1,udp,1194,#USERCERT=user.crt #USERKEY=user.key #TA=ta.key #CERT=ca.colibri.crt #REMOVE=1
...
Austria (UDP),151.236.6.106,udp,111,#REMOVE=2
....
```

Do I need to specify the default CA.crt for all non Colibri locations using `#CERT=ca.crt` tag?

I've updated the timestamp and resolv-retry.

Colibri locations use client cert/key (the same for all users) as well as TLS auth.

All other locations only use CA cert.

**Comment by Zomboided** [comment]
I think ab77's changes fix what you're trying to do vpnarea.

However, these : #USERCERT=user.crt #USERKEY=user.key #TA=ta.key are the default and can be removed.  If the code doesn't do the right thing here, I'll fix it.  With these changes I'm good to merge and do a test to see if what you're proposing works.

**Comment by ab77** [comment]
OK, just added the (hopefully) final change on behalf of VPNArea. I removed the defaults in `LOCATIONS.txt`. Please let me know if there is anything else...

**Comment by Zomboided** [comment]
Merging this so I can test that everything resolves correctly.  Looks fine to me, but vpnarea will need to test that it actually connects

**Comment by ab77** [comment]
Cheers, we'll test it all out over the next few days.

**Comment by Zomboided** [comment]
Yup, user key/cert doesn't work.  Change TEMPLATE.txt like this:

#REMOVE2cert #PATHuser.crt
#REMOVE2key #PATHuser.key

**Comment by ab77** [comment]
https://github.com/Zomboided/service.vpn.manager.providers/pull/19

**Pull request merged**
