### PR TITLE
Update LOCATION.TXT for China users

### PR DESCRIPTION
**Pull request by wensente**
Hello, VPN.AC has dedicated servers for China. I added the best ones at the end of the file. All information concerning these servers are on their website here: "Knowledge base" /knowledgebase/61/Instructions-for-users-in-China.html
Thanks

### CODE REVIEW

**Comment by Zomboided** [comment]
Can you attach the ovpn files that relate to these connections please?  The LOCATION.txt file is generated from them rather than updated directly.  I don't have an account on VPN.ac to get them myself.  Thanks.

**Comment by wensente** [comment]
Oh OK sorry.

They are all here

https://vpnac.com/ovpn/-CHINA-ONLY-PROFILES/

I made a zip with the best ones. I took the AES 128 encryption.
[files.zip](https://github.com/Zomboided/service.vpn.manager.providers/files/1190294/files.zip)

Thank you for your help!

**Comment by Zomboided** [comment]
Thanks, that's just what I need.  I'll take a look over the next couple
days.

**Comment by wensente** [comment]
Thanks, I will finally watch something else than Chinese TV channels :)

When I added lines on your file, it seems it has forked your repo under my name. Can I erase the created repo under my name without any impact on yours? Guess so but I prefer to ask first. Thanks!

**Comment by Zomboided** [comment]
Yeah,nothing you do will affect my repo.  I'll reject the pull first incase
that stops it.

**Comment by Zomboided** [comment]
Also, if you want to try and use the changes you made right now you can put the LOCATIONS.txt in the userdata directory and then reset the VPN provider files.  When you reconnect, it'll pick up your copy.  See the instructions on the wiki for more info

**Comment by wensente** [comment]
Alright, thanks for the info!

**Comment by Zomboided** [comment]
I uploaded an update yesterday. If you reconnect it should pick it up. Let me know if it doesn't work, thanks

**Pull request closed without merging**
