### PR TITLE
Update LOCATIONS.txt

### PR DESCRIPTION
**Pull request by imatasic**
Updated with the current list of locations available on hide.me website

### CODE REVIEW

**Comment by Zomboided** [comment]
Thanks, but this stuff is all generated from .ovpn files provided by the VPN provider.  Do you have/can you share those files?

**Comment by imatasic** [comment]
Yes, can i mail it to you somehow?

**Comment by Zomboided** [comment]
Just attach them here, or open an issue if you can't and attach it to
that.  Check first, but they don't contain any user auth data, just a tls
key and ca cert.  If you see a user key or cert or password, don't post
them.

**Comment by Zomboided** [comment]
Reopen if you find the files

**Pull request closed without merging**
