### PR TITLE
Update LOCATIONS Default Encryption.txt

### PR DESCRIPTION
**Pull request by fapostol**
New locations and updated hostnames.

### CODE REVIEW

**Comment by cristianaghe** [comment]
hello,

@Zomboided me and Filip are both working for PIA and, following up some recent infrastructure changes, we'd like to renew the locations list with the new endpoints and configuration parameters.

Please help us by approving the changes.

Many thanks,
Cristiana Gheorghe

**Review by Zomboided — APPROVED** [review]

**Comment by Zomboided** [comment]
Reverts as this has just broken support.

**Comment by fapostol** [comment]
@Zomboided Can you detail what the issue was? Is it related to the new host names? Do connections fail?

**Comment by Zomboided** [comment]
It didn't connect.  I didn't bother to debug it.  You should have tested it
before you submitted it.
It's been reverted using the set of ovpn files that are currently available
to subscribers.  When you update these, I'll update PIA support.

**Pull request merged**
