### PR TITLE
Add VPN provider Mullvad

### PR DESCRIPTION
**Pull request by yitzhaq**
Hi,

I know you're hesitant to add more providers, but hope you'll consider taking in Mullvad, which stands out in several ways in the jungle of VPN providers. They support IPv6 (they don't just block it), they support WireGuard (not relevant here, of course, but a reason many choose them over others), and they're by far the favorite provider of many a privacy zealot.

https://thatoneprivacysite.net/2017/10/03/mullvad-review/

These files are tested and working, and the location list is up-to-date as of today. The template is based on their suggested settings. Configs for all locations can be downloaded from https://mullvad.net/en/download/config/ and they offer a 3 hour trial with zero questions asked, which can be repeated as needed. Their configs are consistent and predictable across locations, as are their location hostnames.

Thanks in advance for your consideration.

### CODE REVIEW

**Comment by Zomboided** [comment]
I think user defined is effective enough, and I don't want to update any more providers.
If you want this to happen then you need to do this following :

https://github.com/Zomboided/service.vpn.manager.providers/blob/master/AirVPN/METADATA.txt
This is what a valid METADATA.txt looks like.  The number you have as '4' should be the number of files you're offering up, and the list of files should be exactly that.

You need to test this, I'm not going to make any effort to do so.  You can do this by - 
Pick a provider (PIA would work here), try and connect using your mullvad user/pass.  
It'll download the files to /userdata/addon-data/service.vpn.manager/Downloads/PIA (might have this path a bit wrong).
Wait for the connection to fail (because you don't have a valid user/pass).  
Swap out the files in the mentioned directory with yours.  
Use the Reset VPN Provider in settings/utilities, then connect with a valid user/pass for this provider.
Rather than download, it'll just use what's in the downloads directory.

If this works, I'll do this commit and make the changes to support and you can test/maintain any updates

**Comment by yitzhaq** [comment]
I understand you don't wanna spend your time maintaining more providers, and I'd be happy to keep maintaining this one. In fact I would anyway, as I use it actively myself, and a pr doesn't add many extra minutes.

This was already tested in nearly the manner you describe before submitting, but I temporarily overrode raw.githubusercontent.com in /etc/hosts to prevent it from overwriting the files, which seemed to do the trick. I'm currently using these files in place of another provider, and would like to see it merged to I can remove the host override :) I've tested 5 different locations, with both UDP and TCP, and they all work fine. Thus the rest should too, bar any hostname typos.

FWIW I did try to use the user defined approach first, as I understand this is your preference, but I had enough trouble getting it to work that doing this was actually easier, so I figured I might as well contribute. I'd be happy to share details of my troubles with user defined should you be interested, though I suppose that belongs somewhere other than here.

As for this pr, am I correct in understanding that the number of files should *not* include METADATA.txt itself (as in, it enumerates the files listed below the number)? If so, the current number should be correct, and this should be ready for merge.

Thanks - and thanks for a great addon!

**Review by Zomboided — APPROVED** [review]

**Review by Zomboided — APPROVED** [review]

**Comment by Zomboided** [comment]
Try 5.0.1, it on the release page.
Can you also attach the ovpn files for this provider to this request too.  All of the files are generated automatically as it makes it easier and less typo prone.

**Comment by Zomboided** [comment]
And if you have ideas for improving the user defined wizard, open an issue against service.vpn.manager and I'll take a look.

**Comment by yitzhaq** [comment]
Thanks for the swift merge! ovpn archive downloaded from their site (sans u/p) attached.
[mullvad_config_linux_all.zip](https://github.com/Zomboided/service.vpn.manager.providers/files/2100132/mullvad_config_linux_all.zip)

**Comment by yitzhaq** [comment]
Just for future reference, it was grabbed from here: https://mullvad.net/en/download/config/
Platform Linux, Region All, and whatever random account number (not validated, and won't be used anyway). No login required.

**Comment by Zomboided** [comment]
Thanks, couldn't download from the link as the account number did seem to be validated for me.  I used your files and wrote some code to generate everything automatically from them - which makes it much easier and less erorr prone to update things when they change locations.  The formatting isn't as nice as your effort, but the data isn't available to do this, so it is what is it.  Thanks for doing to work to add this.

**Comment by yitzhaq** [comment]
Oh, OK, sorry about that. I just tried with account number 1234, and that was accepted, so I assumed there was no validation. Try that, and you should be able to download directly in the future.
Parsing code obviously makes maintenance a breeze compared to manual updates, I was just trying to save you the trouble. Does this mean you no longer need my efforts to keep this up to date then, or..?

I do see the formatting lost some of the location names, but as you say, it is what it is. Should you ever feel inspired to write code to do any scraping and/or mapping, the full table is available [https://mullvad.net/en/servers/#openvpn](here). It could be it's possible to get the list by querying something under api.mullvad.net as well - let me know if this is anything you'd be interested in pursuing, and I can do some research.

One rather minor thing though; it seems the location list is currently sorted by hostname, rather than location name. Is that intentional, and if not, worth addressing? Just piping it through sort should do the trick.

Thanks again for your efforts.

**Comment by Zomboided** [comment]
The location is always sorted alphabetically, for all providers.

APIs are good, and I have implemented one.  It took 2 weeks of effort.  I'm not going to do that for something that earns me no income :-)

**Comment by Zomboided** [comment]
Also, if you come across updates, post up the zip of configs and I'll run the generator to fix it all up.  Cheers

**Comment by yitzhaq** [comment]
Ah yes, I see now it's sorted in-software, so no need for sorting the file, then.

Can you pull a new update? Seems the list is missing at least 1 location (Gothenburg).
See if you're able to grab it from https://mullvad.net/en/download/config/ with account no. 1234, if not I can zip one up for you.

Cheers

**Comment by Zomboided** [comment]
1234 works...you should see this updated shortly

**Pull request merged**
