### PR TITLE
Windscribe: added Portugal to Locations list

### PR DESCRIPTION
**Pull request by prlm86**
Added Portugal to LOCATIONS.TXT for both UDP and TCP.

### CODE REVIEW

**Comment by Zomboided** [comment]
This file is generated, can you supply the ovpn for this location please?

**Comment by prlm86** [comment]
Here you go!

[Windscribe-PT-ovpn.zip](https://github.com/Zomboided/service.vpn.manager.providers/files/4230297/Windscribe-PT-ovpn.zip)

**Comment by Zomboided** [comment]
Great, thanks, I'll add this in the next few days

**Comment by Zomboided** [comment]
This done now, thanks

**Pull request closed without merging**
