### PR TITLE
Revamped TorGuard profile

### PR DESCRIPTION
**Pull request by yitzhaq**
* Remove several dead locations
* Add 10+ "new" locations
* Remove stealth locations (now only supported in TG Client)
* Harmonize on a unified config across all locations
* Add TCP in addition to UDP
* Harden crypto settings (no more Blowfish, use TLS key)
* Optimize tunnel settings
* Use hostnames for all locations, rather than IPs
* Generally bring config more in line with TorGuard's recommendations

### CODE REVIEW

**Review by Zomboided — CHANGES_REQUESTED** [review]
Hello, are you representing TorGuard?  I'm happy for you to take over maintaining these files if you are, otherwise I'd like to generate them from the ovpn files that TorGuard make available to subscribers.

Assuming you are representing TorGuard, in TEMPLATE.txt, resolve-retry should be 30 as I detect the time out in the addon.  Everything else looks fine.
And

**Comment by yitzhaq** [comment]
Hi,

I don't represent them, no. I'm just a user (and TorGuard customer) who loves your addon (spectacular work you've done - thanks!), but found the existing TorGuard files rather outdated.

For the most part these are based off of TorGuard's OpenVPN config generator, which lets you choose between every available form of OpenVPN supported encryption. I picked the one they recommend by default, which offers a reasonable balance between crypto and performance (considering I expect this to be widely used on low-powered devices such as RPi etc), but better crypto than the existing files.

The few changes I made on top of the generated config (larger send/receive buffer, don't cache auth in mem etc) are more generic optimizations, but I did run them (and the rest of this pull request) by TorGuard support for good measure, and they gave thumbs up. Hope that is sufficient.

I'll submit an update with adjusted resolve-retry.
BTW, was there supposed to be anything more after that final "And"? :)

**Comment by yitzhaq** [comment]
Should you want to verify, you can view downloadable profiles here:
https://torguard.net/downloads.php

The config generator, as well as the full port specs and location list, are only available behind a login. Where inconsistencies exist (such as the recommended tls-ciphers setting only appearing on the port specs page), I have made a best effort to harmonize. As you may notice, there are also differences between the downloadable profiles offered for mobile, (ASUS) routers and generic. Here, too, I have tried to find a reasonable middle ground.

**Comment by Zomboided** [comment]
Ok, thanks...I'll go ahead and merge this as I don't have a TorGuard ID anymore.  Please test the changes when you see them arrive and let me know if there are issues.  Someone else was moaning at me that this wasn't working this morning, so this is good timing.

**Comment by yitzhaq** [comment]
Thanks for the merge. Verified five different locations, and tested a stream through London for several hours without issue. Barring any possibly typos in locations I didn't test, it all looks good to me!

(For the record, testing was performed using OpenVPN 2.4.0-4 running on Ubuntu 17.04)

**Comment by Zomboided** [comment]
Nice one, thanks for your help.

**Pull request merged**
